### ISSUE TITLE
[BUG] [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.

### ISSUE THREAD

**Issue by MilNoslen** [bittorrent/go-btfs#307] opened 2023-03-30 21:57 UTC
**Describe the bug**
[WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.

**To Reproduce**
Simply starting BTFS.exe

**Expected behavior**
To not give an error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Edition	Windows 10 Home
Version	22H2
Installed on	‎5/‎28/‎2021
OS build	19045.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

 - Version go-btfs version: 2.3.1-c0fbaee

**Additional context**
First time happening for me. Upgraded from 2.3.0 to current

**Comment by Richard2GitHub** [comment] 2023-03-31 10:45
Hi, MilNoslen. It's a warning-level message related to node discovery within the local network. You can ignore it.

**Comment by azrielitay** [comment] 2023-03-31 12:22
Its not stopping ... its show for every 2 sec
2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.

Will it be fixed?

**Comment by Gromozecka** [comment] 2023-03-31 14:54
After updating to 2.3.1, constant errors. How to deal with it?
2023-03-31T16:14:29.133+0300    ←[31mERROR←[0m  autorelay       autorelay/autorelay.go:80       failed to start relay finder    {"error": "relayFinder already running"}
2023-03-31T17:02:56.867+0300    ←[31mERROR←[0m  core/commands   commands/wallet.go:248  wallet get balance failed, ERR: Failed to get ledger balance, reason: EscrowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc error: code = InvalidArgument desc =
2023-03-31T17:44:30.714+0300    ←[31mERROR←[0m  autorelay       autorelay/autorelay.go:80       failed to start relay finder    {"error": "relayFinder already running"}

**Comment by MilNoslen** [comment] 2023-04-02 03:11
> 

Okay, so it's a low warning, but it's non-stop every few seconds.

**Comment by Gromozecka** [comment] 2023-04-02 04:36
2023-04-02T03:23:47.212+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:41:47.556+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:41:47.556+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:41:47.556+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:44:47.605+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:44:47.605+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:44:47.605+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:47:33.975+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode
2023-04-02T03:56:51.792+0300    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode

**Comment by Gromozecka** [comment] 2023-04-02 04:37
2023-04-02T01:00:43.486+0300    ←[31mERROR←[0m  autorelay       autorelay/autorelay.go:80       failed to start relay finder    {"error": "relayFinder already running"}

**Comment by Richard2GitHub** [comment] 2023-04-02 16:07
Hi, @Gromozecka, About '{"error": "relayFinder already running"}', this error message is caused by the upstream go-libp2p library. There is an issue related to it on GitHub at https://github.com/libp2p/go-libp2p/issues/2234. The problem may be resolved once the related PR is merged.

**Comment by brianbc2021** [comment] 2023-04-03 03:33
> 

Have you tried the 'btfs log level all error' command? This command will set the log level to error, it will suppress warn level log.

**Comment by brianbc2021** [comment] 2023-04-03 03:34
> Its not stopping ... its show for every 2 sec 2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:36 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:37 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:55 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied. 2023/03/31 15:17:56 [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.
> 
> Will it be fixed?

Have you tried the 'btfs log level all error' command? This command will set the log level to error, it will suppress warn level log.

**Comment by Richard2GitHub** [comment] 2023-04-03 07:32
Hi, @MilNoslen You can change 'Discovery.MDNS.Enabled' in config to 'false' to suppress it. 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/122080967/229441124-f45ac413-befc-4a65-af84-b025fc5a876b.png">

**Closed** 2023-04-03 09:20 UTC

**Comment by MilNoslen** [comment] 2023-04-05 20:17
> Hi, @MilNoslen You can change 'Discovery.MDNS.Enabled' in config to 'false' to suppress it. <img alt="image" width="325" src="https://user-images.githubusercontent.com/122080967/229441124-f45ac413-befc-4a65-af84-b025fc5a876b.png">

Where do I change this exactly?

I see a config file with no extension in the folder, and I can open it in notepad to edit it. I changed it to false, but I'm still getting the WARN mdns.

**Comment by Raimis999** [comment] 2023-04-12 16:55
> After updating to 2.3.1, constant errors. How to deal with it? 2023-03-31T16:14:29.133+0300 ←[31mERROR←[0m autorelay autorelay/autorelay.go:80 failed to start relay finder {"error": "relayFinder already running"} 2023-03-31T17:02:56.867+0300 ←[31mERROR←[0m core/commands commands/wallet.go:248 wallet get balance failed, ERR: Failed to get ledger balance, reason: EscrowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc error: code = InvalidArgument desc = 2023-03-31T17:44:30.714+0300 ←[31mERROR←[0m autorelay autorelay/autorelay.go:80 failed to start relay finder {"error": "relayFinder already running"}

The same i have after update from 2.3.0 to 2.3.1

**Comment by MilNoslen** [comment] 2023-05-29 01:00
Hi, @MilNoslen You can change 'Discovery.MDNS.Enabled' in config to 'false' to suppress it. image

Where do I change this exactly?

I see a config file with no extension in the folder, and I can open it in notepad to edit it. I changed it to false, but I'm still getting the WARN mdns.

D:\btfs2\btfs.exe config Discovery.MDNS.Enabled false
Error: failed to set config value: failure to decode config: json: cannot unmarshal string into Go struct field MDNS.Discovery.MDNS.Enabled of type bool (maybe use --json?)
