### ISSUE TITLE
Nodes override each other between testnet and mainnet

### ISSUE THREAD

**Issue by pkyriacou** [bittorrent/go-btfs#92] opened 2022-02-26 07:49 UTC
Hello,

I have been running 2 nodes with the same Host ID, one in testnet and one in mainnet. I have noticed that in both scan.btfs.io and scan-test.btfs.io, the two nodes conflict with each other. I know it is wrong to use the same private key on multiple hosts, but I was expecting complete separation between testnet and mainnet. This does not seem to be the case.

Node 1: Mainnet, v2.1.0
Node 2: Testnet, v2.0.2

Currently, when I look at the **mainnet** node's Host id in scan.btfs.io, it shows that I'm using v2.0.2, which I am not. It also shows the data (storage allocated/utilized) of the testnet node! Not only that, but its Host Score has dropped from 10 to 9, as it detects that I'm not using the latest version (it says I'm using v2.0.2 in mainnet!). When I check the Host id in testnet, it shows that the node is offline (no info is given), even though the node is actually running.

It doesn't seem to be just a bug on the BTFS Scan website, given that the Host score has also been affected. The hosts override each other, even though they are in separate chains, which shouldn't happen. I've tried running one after the other and the information in BTFS Scan changes according to the last node to start.

Also note that if the Host score hadn't changed, and I hadn't looked at BTFS Scan, I wouldn't have even known that this issue exists!

**Comment by Sophia-yu-kk** [comment] 2022-02-28 08:17
Please provide us with your node id, we will check it for you.

**Comment by pkyriacou** [comment] 2022-03-11 15:59
Kindly note that since 09/03 I have turned off the aforementioned testnet node. Mainnet node is still operational. The issue still existed at the time I turned off the testnet node.

Please let me know if I can be of any assistance.

**Comment by Robin-Luooo** [comment] 2022-03-14 06:27
Hi, I'm sad this confused you. I know that you want to share the private key both in testnet and maintest, this is a common case. And I want to know whether you started your testnet node and mainnet node with different `$BTFS_PATH` env? 

The node stores its data and configs in the `$BTFS_PATH` with a default value `~/.btfs`. It seems that you started two nodes with the same `$BTFS_PATH`, so that their data conflicts with each other. You can find the `$BTFS_PATH` with echo command, e.g. `echo $BTFS_PATH`.

You can solve the problem as following.

1. Download the latest [go-btfs version 2.1.1](https://github.com/bittorrent/go-btfs/releases/tag/btfs-v2.1.1), which supports importing private key in `init` command.
2. Set a proper `$BTFS_PATH` in order to separate the data between testnet and mainnet nodes. Then start your testnet node and get its private key.

```shell
# set a different BTFS_PATH for testnet is recommend, ~/.btfs.testnet for example
$ export BTFS_PATH=~/.btfs.testnet

# start your testnet node using init and daemon command

# find the private key you want to share with mainnet node
$ cat ~/.btfs.testnet/config | grep HexPrivKey
# $ cat ~/.btfs/config | grep HexPrivKey   # when your BTFS_PATH is ~/.btfs
"HexPrivKey": "<your_private_key>"
```

3. Using the private key to start the mainnet node. You may encounter a port conflict problem if you run testnet and mainnet nodes at the same time without modify their listening port in the config file under `$BTFS_PATH`. You can modify the listening ports in config file's `Addresses` part.

```shell
# set a different BTFS_PATH for mainnet, or using the default value ~/.btfs will be ok
export BTFS_PATH=~/.btfs.mainnet

# init the node with the private key
btfs init -i <your_private_key>

# change the listening ports in the config file.
# A better way is to modify the testnet's config, and let the mainnet's config not changed.
# e.g.
# "Addresses": {
#     "API":"/ip4/127.0.0.1/tcp/5002",
#     "Announce":[],
#     "Gateway":"/ip4/127.0.0.1/tcp/8082",
#     "NoAnnounce":[],
#     "RemoteAPI":"/ip4/127.0.0.1/tcp/5102",
#     "Swarm":[
#         "/ip4/0.0.0.0/tcp/4002",
#         "/ip6/::/tcp/4002",
#         "/ip4/0.0.0.0/udp/4002/quic",
#         "/ip6/::/udp/4002/quic"
#     ]
# }

# start the mainnet node
btfs daemon --chain-id=199
```

**Comment by Robin-Luooo** [comment] 2022-03-15 08:44
Hi @pkyriacou, thanks for your feedback, I have noticed that your mainnet host is upgrade to v2.1.1 and works well now.

As for your original problem, I guess the main reason is that you have tried to start the testnet host using the mainnet host's config without adapting. As a consequence the testnet host affected the mainnet host's data display at the scan.btfs.io.

Just as I [aforementioned](https://github.com/bittorrent/go-btfs/issues/92#issuecomment-1066426243), using the `-i` argument to reuse the private key will be more convenient and less likely to go wrong. And although we can run two hosts in mainnet and testnet using the same private key, but it's better not to start multiple hosts in mainnet using the same private key.

And as for your host's score dropped from 10 to 9, is caused by another little problem, which is in the process of optimization. And will be released latter.

**Closed** 2022-03-21 07:39 UTC
