### ISSUE TITLE
BTFS 2.3.0 daemon keeps failing after a few days

### ISSUE THREAD

**Issue by Rchua72** [bittorrent/go-btfs#300] opened 2023-02-07 22:53 UTC
Ever since I upgraded to BTFS 2.3.0, I noticed that the btfs daemon keeps failing after a few days.  It wasn't happening like this before.  I used to leave the daemon running for weeks.  I have attached a screenshot of my terminal to help debug this issue.

![btfsterminal](https://user-images.githubusercontent.com/6827300/218254689-9ed5889c-2176-48c2-a622-613611602935.png)

**Comment by solipsist01** [comment] 2023-02-09 18:03
you're probably getting out of memory on your pi.

**Comment by Andrju81** [comment] 2023-02-09 18:36
> you're probably getting out of memory on your pi.

I have the same problem.
The documentation says that for the normal operation of the node, you need free 2 GB of RAM, I have more than 2 GB of RAM on the server, but the btfs daemon process consumes all available physical RAM and even fills the entire swap file, which is why the system simply kills the btfs daemon process.
There are no problems with this on a physical PC, the btfs daemon takes less than 100 MB of RAM.

**Comment by penn202000** [comment] 2023-02-10 03:58
The process might be killed by os kernel because of resource starvation: https://stackoverflow.com/questions/726690/what-killed-my-process-and-why

**Comment by Rchua72** [comment] 2023-02-11 11:08
My PI has 4GB of RAM so it shouldn't run out of memory.  They need to optimize the memory consumption.

**Comment by solipsist01** [comment] 2023-02-11 11:52
They should indeed.

**Comment by Andrju81** [comment] 2023-02-11 23:41
I increased the paging file from 1.5 GB to 4 GB, the flight was normal for a day, but the btfs demon uses all the free RAM memory from 90% to 93%, this is just what I managed to notice.
![RAM91 8_2023-02-12_00_57_16](https://user-images.githubusercontent.com/40444286/218285647-ed273f6f-7084-4384-8b10-8a3ee13f8a17.png)

**Comment by penn202000** [comment] 2023-02-12 06:57
My VPS used almost 5G mem to run btfs daemon
<img width="934" alt="image" src="https://user-images.githubusercontent.com/101245718/218297497-5c09f740-6950-4ced-9782-817bc6a98e4d.png">

**Comment by penn202000** [comment] 2023-02-15 11:35
> 100mb seems impossible to me... ive seen it take 4gb. Since 2.3 indeed

Me too, I just installed a new node, 3G mem, and 3G swp. No other process or app but Only the btfs daemon is running on this VPS. Consume about 800M mem. 
![Uploading image.png…]()

**Comment by ruXlab** [comment] 2023-02-16 16:23
My experience: it can eat up 30% of 20Gb (~8Gb according to htop) and then die - I've been observing this behaviour for half year at least. So it's the best to run it as systemd unit that supports restarts OR `while [ true ]; ./btfs ... ; done` if run in screen

**Comment by Shawn-Huang-Tron** [comment] 2023-02-17 10:55
@Rchua72 Before BTFS 2.3.0,  this problem never happen to you?

**Comment by Rchua72** [comment] 2023-02-17 20:41
This problem did not happen for me before 2.3.0.

**Comment by NWC29** [comment] 2023-02-19 17:12
congratulations gentlemen I don't understand you much but I feel comfortable, I will learn from you

**Comment by Richard2GitHub** [comment] 2023-02-24 04:04
@Rchua72  Thanks for the report; the devs team has taken action to optimize the memory consumption, and the optimization will be included in the next version.

**Closed by Richard2GitHub** 2023-02-24 04:04 UTC

**Comment by oldcityws** [comment] 2023-02-24 22:28
@Richard2GitHub does this include the HDD space that it is hogging?  I notice that I am losing availability of about 1GB per day - I am on Windows and see the HDD space available go down and only figured out that this could be caused by BTFS after a few system reboots that suddenly freed up HDD space each time, and the only thing I had constantly running was BTFS.

**Comment by Richard2GitHub** [comment] 2023-02-27 03:46
Hi, @oldcityws  have you checked the specific dir used by BTFS(the path you configured)?

**Comment by oldcityws** [comment] 2023-02-27 16:22
The actual directory seems fine with 229 MB of data used.  I think it's physical HDD space being used in lieu of memory that's causing the drive space to be used up.  At one point over 40GB available went down to less than one GB available.. and then a Windows update caused a reboot.  Now it's hovering near 37 GB available and counting down.  Maybe a memory leak is somewhere?

**Comment by oldcityws** [comment] 2023-02-28 07:18
It is the pagefile increasing in size to accommodate more and more RAM needed only there is not enough RAM so Windows pagefile feature is in use.  Pagefile is HDD space used to take the load off of the physical RAM when memory is in demand but not available.

**Comment by Richard2GitHub** [comment] 2023-02-28 09:09
Hi, @oldcityws. The devs team has taken action to optimize the memory consumption.
I'm not sure what happened in the background about the pagefile taking up more space. I googled the pagefile mechanism and found this 'https://social.technet.microsoft.com/Forums/en-US/2ad6c8f8-4906-4e8f-b250-da5b2f09996b/virtual-memory-pagefile-taking-up-more-and-more-space?forum=win10itprogeneral'. To stop the btfs daemon process and keep windows running some time is a good way to find out what consumes the space.

**Comment by oldcityws** [comment] 2023-02-28 09:29
Thank you, I will have to monitor my system to see what exactly is hogging HDD space via pagefile.
