### ISSUE TITLE
CHEQUES are not cashed in full?!...

### ISSUE THREAD

**Issue by Andrju81** [bittorrent/go-btfs#299] opened 2023-02-05 02:46 UTC
When cashing out CHEQUES in BTFS Dashboard, there was a partial cashing out of CHEQUES and not a full one!?...
My HOST ID: 16Uiu2HAmH8xCNBgVHnwrhn1ehyzg49zs8C3FwCAwGzkKdsqY9BmS
![Clip2Net Menu_2023-02-05_05_28_23](https://user-images.githubusercontent.com/40444286/216798785-cf6ee454-fb13-44d3-b2d7-8dacf52547b7.png)
![Clip2Net Menu_2023-02-05_05_31_37](https://user-images.githubusercontent.com/40444286/216798793-8bb158e9-e80b-461c-9d3a-8e8ed0f91ab2.png)
![Clip2Net Menu_2023-02-05_05_32_28](https://user-images.githubusercontent.com/40444286/216798799-32033ed8-ad6d-40c5-acfd-4c303a6017bf.png)
![Clip2Net Menu_2023-02-05_05_33_23](https://user-images.githubusercontent.com/40444286/216798805-eeeb0328-7bf7-47ff-bbc8-55392ce1685e.png)

**Comment by Richard2GitHub** [comment] 2023-02-06 10:39
Hi, @Andrju81. It's caused by inconsistency of the data, have you ever recover your host in another machine or directory by the same private key?  The solution is: remove this node(abandon the local data) and install a new BTFS node (ref: https://docs.btfs.io/docs/install-run-btfs20-node).

**Comment by Andrju81** [comment] 2023-02-06 19:01
> Hi, @Andrju81. It's caused by inconsistency of the data. Have you ever recovered your host in another machine or directory with the same private key? The solution is: to remove this node(abandon the local data) and install a new BTFS node (ref: https://docs.btfs.io/docs/install-run-btfs20-node).

Good day!
So you are suggesting that I delete the old reward node (Badge BTFS 2.0 Genesis G Level) and start a new one?
And why breed a bunch of nodes and unnecessary wallets?
Isn't it easier to fix this error by displaying data only for current transactions?!...

**Comment by Shawn-Huang-Tron** [comment] 2023-02-07 03:45
We have fixed this kind of cheque issues since BTFS2.3.0, but some data origined before this can't be mended because some data is caculated based on your vault contract. So we recommend you to upgrade the latest version of btfs and create a new node.

**Comment by Andrju81** [comment] 2023-02-07 04:29
> We have fixed this kind of cheque issues since BTFS2.3.0, but some data origined before this can't be mended because some data is caculated based on your vault contract. So we recommend you to upgrade the latest version of btfs and create a new node.

When upgrading to BTFS 2.3.0, I did everything according to the instructions described on this link - https://docs.btfs.io/docs/node-migration-instructions-documentation
Specifically, the second point:
2. Migrate without stats and revenue from the old node
Set the value of the BTFS_PATH environment variable of the new node to the updated node file and the configuration path (do not use the same repo path from the existing BTFS nodes)
Run btfs init -p -i on the new node
Start btfs daemon on the new node
But in the end, nothing has changed - there are no old statistics, but they are taken into account and distort the current results.

**Comment by Shawn-Huang-Tron** [comment] 2023-02-07 10:34
Do you expose your BTFS_PATH environment to the new path? Suggest you to drop the old .btfs dir and reinstall the btfs.

**Comment by Andrju81** [comment] 2023-02-07 14:54
> Do you expose your BTFS_PATH environment to the new path? Suggest you to drop the old .btfs dir and reinstall the btfs.

I installed version BTFS 2.3.0 on a new server with a freshly installed OS Ubuntu Server, and did everything you describe, but as you can see on the screenshots, nothing has changed.

**Comment by Shawn-Huang-Tron** [comment] 2023-02-17 10:41
Sorry to disturb you. What I mean is that the CHEQUES cause by this renter node and your node could't be fixed because of the vault contracts. So you can't run btfs init -i... You should start a total new node. And we confirm that it will work fine.

**Comment by Andrju81** [comment] 2023-02-17 12:16
> Sorry to disturb you. What I mean is that the CHEQUES cause by this renter node and your node could't be fixed because of the vault contracts. So you can't run btfs init -i... Your peer id needs to be changed. You should start a total new node. And we confirm that it will work fine.

This is not a solution to the problem, but a way out of a problem that will manifest itself in the future when moving a new node to a new server without saving history, that is, with the command btfs init -i ...

**Comment by FRiceSchoolAcct** [comment] 2023-02-19 13:55
That's a known issue caused by data inconsistency in an older version(v2.1 or v2.2, I'm not sure now). The way to handle it is to start a new node. And the data inconsistency can not be resolved by migrating to a new env(vps). I've tried to clean local data before, copy .btfs dir to a new vps, or restore the vps snapshot, but it didn't work as expected. After cleaning the whole btfs dir and reinstalling a new one, which means generating a new hostId. For now, everything is going well.

**Comment by NWC29** [comment] 2023-02-19 17:04
Help, I have been with the active node for days and blank checks appear with the following note:

LastSendCheques map() <nil>

Does anyone know why and what can I do?

good weekend

BTTC 0xfD998888EC60886dBCEcb9BE1881B7eA490480f8

ID host 16Uiu2HAmNTZ86Ewd37YHcYMms1w77ouVxS1tE3J6Ykk9eu1y9ntA

**Comment by Andrju81** [comment] 2023-02-19 18:02
> That's a known issue caused by data inconsistency in an older version(v2.1 or v2.2, I'm not sure now). The way to handle it is to start a new node. And the data inconsistency can not be resolved by migrating to a new env(vps). I've tried to clean local data before, copy .btfs dir to a new vps, or restore the vps snapshot, but it didn't work as expected. After cleaning the whole btfs dir and reinstalling a new one, which means generating a new hostId. For now, everything is going well.

If you received checks and cashed them, you can check that nothing has changed by following this instruction - https://docs.btfs.io/docs/node-migration-instructions-documentation
2. Migrate without stats and revenue from the old node
And I repeat again that this is not a contract error, the error is precisely in the algorithm for counting checks and the amount of funds at the time of node initialization using the btfs init -i ...
All this can be seen on the screenshots, the node was installed without stats and revenue from the old node with the old host id.

**Comment by Richard2GitHub** [comment] 2023-02-24 08:46
Hi, @Andrju81 , before 2.3.0, this kind of cheque issue can't be mended by migrating to a new node.

> We have fixed this kind of cheque issues since BTFS2.3.0, but some data origined before this can't be mended because some data is caculated based on your vault contract. So we recommend you to upgrade the latest version of btfs and create a new node.

**Comment by theguy39** [comment] 2023-02-24 08:46
I had one I lost some on from my vault not letting me take funds out in a previous version, look at it this way its not even a penny your loosing and there getting kinks out a the way now before were all making real money take it from someone who made couple grand off of this mining before it broke for a year for me. 

So either cut your losses when you get a corrupt install if its new or, save your config file from your .btfs folder it installed to, run the new install once (Personally an install for me is download version 2.3.0 again (https://github.com/bittorrent/go-btfs/releases/tag/btfs-v2.3.0) after run it once and whines for fee to activate new wallet. Close it navigate to the .btfs folder and put your old config back in place of the new wallet one it made then run it again see if can get your contract to show right. That will put your old wallet back in. I've transfered wallets to other larger HDD's. Hell if you need make new wallet in end send me your wallet Ill drop you the fees to activate it! just need the BTT wallet and Ill gladly help out a fellow miner. 

This is the future guys its gonna be the next BTC in the way of data storage and its Genius. I see where there aiming for and it makes rich save and little guys money and so much more. There only problem right now is they have so much data and a GUI to configure smoothly. By my count with the fastest internet on the planet maybe in 2 years they will have upto todays data uploaded. I see the level and am in awe of the innovation off what there doing. Just hope they can transfer coin to TRX in the GUI browser and also Fix the dam memory leak deff seems like there is a memory leak that fills ram.

Message me regardless we can trade settings I have some nice ones that seem to work on everything from my 25 year old Cor 2 duos to my Ryzen 5900x - I'm not always on here but should be on medical leave soon so why not
[Andrju81](https://github.com/Andrju81)

**Comment by Richard2GitHub** [comment] 2023-02-27 03:43
Hi, @Andrju81 If you encounter any further issues or have any feedback while using the new version on the new node, please don't hesitate to let us know. Thank you again for your contribution!

**Closed by Richard2GitHub** 2023-02-27 03:43 UTC

**Comment by theguy39** [comment] 2023-02-27 14:33
I will remake rhebticketnwhen i have the sxreen shots i do have them but
can you answer a question how much does the contact manager and the host
low water and high water settings affect the ram

**Comment by Andrju81** [comment] 2023-02-27 18:35
> I will remake rhebticketnwhen i have the sxreen shots i do have them but can you answer a question how much does the contact manager and the host low water and high water settings affect the ram
> 

I don't quite understand you. Would you not paraphrase your question in an understandable language?
