### ISSUE TITLE
Error escrow client

### ISSUE THREAD

**Issue by chris110110** [bittorrent/go-btfs#323] opened 2023-06-11 06:06 UTC
Hello btfs Team,
I get always this error:

2023-06-11T08:02:23.798+0200	ERROR	core/commands	commands/wallet.go:248	wallet get balance failed, ERR: Failed to get ledger balance, reason: EscrowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc error: code = InvalidArgument desc = 

What can i do?

Thank you.
Regards,
Chris

**Comment by CrCati** [comment] 2023-06-12 06:03
Hi, @chris110110; thank you for your feedback, it is a deprecated function, and you can ignore it. AFAIK it will be fixed in the next version.

**Comment by chris110110** [comment] 2023-06-12 06:10
Thank you for your answer.
But since this issue i got 0 contracts.

2023-06-12T00:02:20.179+0200	ERROR	reprovider.simple	simple/reprovide.go:130	insecure hash in reprovider, bafkqc4asebkoid4ka6zdbyp7f5e7zj7h7u3qsxxqfhob7myp6wok32ayjqtek (potentially insecure hash functions not allowed)

Regards,
Chris

**Comment by CrCati** [comment] 2023-06-13 10:52
Hi, @chris110110 ,could you tell me the environmental details and the steps to reproduce this error?(reprovider.simple simple/reprovide.go:130 insecure hash in reprovider):


**To Reproduce**
Steps to reproduce the behavior:
1. Execute command '....'
2. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Version [e.g. 2.2.1]

**Additional context**
Add any other context about the problem here.

**Comment by chris110110** [comment] 2023-06-14 21:12
![Screenshot_20230614_230903_RVNC Viewer.jpg](https://github.com/bittorrent/go-btfs/assets/59182112/f73544a0-6666-486e-a6f2-57e5f3093a28)

Hello,

My System is Raspberry pi 4;

The issue is since im running the latest btfs version 2.3.1

Regards,
Chris

**Comment by CrCati** [comment] 2023-06-15 03:44
Hi, @chris110110 thanks for your feedback. You can simply ignore it. It won't affect the reception of your contract.

**Comment by chris110110** [comment] 2023-06-15 04:22
![Screenshot_20230615_061946_RVNC Viewer.jpg](https://github.com/bittorrent/go-btfs/assets/59182112/dfd928c7-a2f5-4b9f-b7ba-e21599a2bfb2)

Hello,
Thank you for your help.
But since this issue i have 0 contracts.
Is it really true?

Regards,
Chris

**Comment by oldcityws** [comment] 2023-06-15 05:35
I have had zero contracts since I started my node... nine months ago.  I am honestly wondering what is wrong that I am not seeing.  100% uptime on very high-speed network with zero contracts.

https://gateway.btfs.io/btfs/QmemV4r3ceK87AjRYc8C663cMauKrvyPKNYbKo5sErA6yC/#/node/16Uiu2HAm2YXoZAyKbTYBVBJJ3wEQ8xFEjsroSjeiTN948HCTRzCd

**Comment by FRiceSchoolAcct** [comment] 2023-06-15 06:00
@chris110110 Did you delete any data in your repository? I think you can try migration to fix it or simply ignore it. The ref link is: https://docs.btfs.io/docs/node-migration-instructions-documentation

**Comment by chris110110** [comment] 2023-06-15 06:12
> @chris110110 Did you delete any data in your repository? I think you can try migration to fix it or simply ignore it. The ref link is: https://docs.btfs.io/docs/node-migration-instructions-documentation

Hi,

No i changed nothing.
I only exchanged the new btfs file.

Then i startet like usual with:
btfs daemon --chain-id 199

Regards,
Chris

**Comment by FRiceSchoolAcct** [comment] 2023-06-15 10:26
Did restarting the node resolve the error message?

**Comment by chris110110** [comment] 2023-06-15 11:46
> Did restarting the node resolve the error message?

No it did not resolve.
I restarted several times....

**Comment by CrCati** [comment] 2023-06-25 03:53
Hi, @chris110110, please try the following steps:
1. btfs pin rm ${cid}
2. btfs block rm ${cid}

Afterward, restart your node to see if the message still pops up.

**Comment by chris110110** [comment] 2023-06-25 04:07
> Hi, @chris110110, please try the following steps:
> 1. btfs pin rm ${cid}
> 2. btfs block rm ${cid}
> 
> Afterward, restart your node to see if the message still pops up.

![Screenshot_20230625_060532_RVNC Viewer.jpg](https://github.com/bittorrent/go-btfs/assets/59182112/406c46e6-cba1-4b54-bd44-db5303b6c3de)

Thanks for your answer.
Is it correct what i did?
Regards,
Chris

**Comment by CrCati** [comment] 2023-06-25 06:21
Please replace 'cid' with the string you provided earlier: bafkqc4asebkoid4ka6zdbyp7f5e7zj7h7u3qsxxqfhob7myp6wok32ayjqtek

**Comment by CrCati** [comment] 2023-06-30 03:40
Hi, @chris110110; I am going to close this issue for now. However, if the issue still persists or if there are new developments, please feel free to reopen it.

**Closed by CrCati** 2023-06-30 03:40 UTC

**Comment by chris110110** [comment] 2023-06-30 10:16
Sorry for my late answer.
I was on Business Trip.
So i tested your commands today and i got this messages.
WhatsApp my failure?
![Screenshot_20230630_121059_RVNC Viewer.jpg](https://github.com/bittorrent/go-btfs/assets/59182112/562c6710-c487-4010-9438-7195525223e0)

Thanks a lot for your help.
Regards,
Chris
